version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - redis
      - mongodb

  redis:
    image: redis:latest
    ports:
      - 6379:6379
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
  celery-worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    depends_on:
      - redis
      - mongodb
    command: celery -A flask_app.celery worker --loglevel=info

  tests:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    depends_on:
      - redis
    command: pytest tests
volumes:
  mongodb_data: