name: Docker Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Build Docker image
        run: docker build -t flask_app .

      - name: Start Docker container
        id: start_container
        run: |
          container_id=$(docker run -d --network host flask_app)
          echo "::set-output name=container_id::$container_id"

      - name: Wait for container to start
        run: sleep 10

      - name: Get container ID
        run: echo "Container ID: ${{ steps.start_container.outputs.container_id }}"

      - name: Run tests
        run: |
          container_id="${{ steps.start_container.outputs.container_id }}"
          docker exec $container_id python -m pytest
          docker logs $container_id

      - name: Stop Docker container
        run: |
          container_id="${{ steps.start_container.outputs.container_id }}"
          docker stop $container_id
