name: Docker Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Build Docker image
        run: docker build -t flask_app  .

      - name: Start Docker container
        run: docker run -d --name flask_app  --network host flask_app 

      - name: Wait for container to start
        run: sleep 10

      - name: Run tests
        run: docker exec flask_app  python -m pytest

      - name: Stop Docker container
        run: docker stop flask_app 
