name: Docker Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Build Docker image
        run: docker build -t flask_app .

      - name: Start Docker container
        id: start_container
        run: |
          docker run -d --network host --name flask_app_container flask_app
          echo "::set-output name=container_name::flask_app_container"

      - name: Get container ID
        id: get_container_id
        run: |
          container_name=${{ steps.start_container.outputs.container_name }}
          container_id=$(docker ps -aqf "name=$container_name")
          echo "::set-output name=container_id::$container_id"

      - name: Run tests
        run: |
          container_id=${{ steps.get_container_id.outputs.container_id }}
          docker exec $container_id python -m pytest

      - name: Stop Docker container
        run: |
          container_id=${{ steps.get_container_id.outputs.container_id }}
          docker stop $container_id
