name: Docker Test

on:
  push:
    branches:
      - main
      - '*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: docker/compose:1.29.2
      volumes:
        - .:/app
      services:
        redis:
          image: redis
          ports:
            - 6379:6379
          options: --entrypoint redis-server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Build and start containers
        run: |
          docker-compose up -d

      - name: Install dependencies
        run: |
          docker-compose run --rm app sh -c "python -m pip install --upgrade pip && pip install -r requirements.txt"

      - name: Run Celery worker
        run: |
          docker-compose run --rm celery-worker celery -A flask_app.celery worker --loglevel=info --concurrency=4

      - name: Run tests
        run: |
          docker-compose run --rm tests pytest
